name: ci

on:
  # Trigger when a push is made to master.
  push:
    branches:
      - master
  # Trigger when a pull request is made against master.
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: |
          bazel build //...
          bazel test //...
